Markdown line

In [1]:
import numpy as np

In [2]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
X.shape

(3, 3)

In [4]:
np.mean(X)

5.0

In [5]:
np.sum(X)

45

In [6]:
np.std(X)

2.5819888974716112

In [7]:
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
X = np.array([[1,2,3],[4,5,6],[7,8,9],[7,2,1],[5,9,3]])

In [11]:
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [7, 2, 1],
       [5, 9, 3]])

In [12]:
X.shape

(5, 3)

In [14]:
X[:,1].max()

9

Column normalization gets rid of scale.  Having variables in different scales could be dangerous.
Through normalization, each feature is reduced to lie between 0 and 1.  Hence all points now lie in the unit hyper-cube next to the origin

In [15]:
import pandas as pd

In [16]:
df = pd.DataFrame(X)

In [17]:
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
3  7  2  1
4  5  9  3

In [20]:
Y = np.array(df[[0,1]])

In [21]:
Y

array([[1, 2],
       [4, 5],
       [7, 8],
       [7, 2],
       [5, 9]])

In [37]:
Z = np.cov(np.array(df[0]),np.array(df[1]))
Z

array([[  6.2 ,   3.05],
       [  3.05,  10.7 ]])

In [36]:
Z.shape

(2, 2)

In [40]:
Z

array([[  6.2 ,   3.05],
       [  3.05,  10.7 ]])

In [30]:
np.array(df[0]).shape

(5,)

In [39]:
np.cov(X).shape

(5, 5)

In [35]:
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [7, 2, 1],
       [5, 9, 3]])

In [ ]:
df1